spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/globus
    username: globus
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:/db.changelog/changelog-main.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    # show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

feign.client.config.currency-feign-client:
  connect-timeout: 5000
  read-timeout: 5000
  loggerLevel: BASIC

app:
  controller:
    base-path: '/api/v1'
    registration-path: '/registration'
    users-path: '/users'
    accounts-path: '/accounts'
    currencies-path: '/currencies'

    endpoints:
      registration: "${app.controller.base-path}${app.controller.registration-path}"
      users: "${app.controller.base-path}${app.controller.users-path}"
      accounts: "${app.controller.base-path}${app.controller.accounts-path}"
      currencies: "${app.controller.base-path}${app.controller.currencies-path}"

  kafka:
    enabled: true
    bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS://localhost:9092}
    currency-topic: currency-topic
    group-id: currency-group

  headers:
    user-email: 'X-User-Email'
    password: 'X-Password'

  zone: 'Europe/Moscow'
  currency-scheduler:
    enabled: true
    type: # mock # real scheduler in any case without mock
    update-currencies:
      cron: '0 0 4 * * *'

  currency-feign-client:
    host: https://cbr.ru
    url: /scripts/XML_daily.asp
    get-currencies.date-req.pattern: 'dd/MM/yyyy'

  db-init.add-currencies.enabled: true

logging:
  level:
    org.apache.kafka: WARN