spring:
  datasource:
    url: jdbc:h2:mem:db;LOCK_TIMEOUT=60000
    username: test
    password: test
    driverClassName: org.h2.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  kafka.enabled: false
  currency-scheduler.enabled: false
  db-init.add-currencies.enabled: false
